config/routes.rb
Rails.application.routes.draw do

  root 'stocks#index'
  
  resources :categories
  resources :journals
  resources :journal_types
 
  resources :locations
  resources :products

 
  resources :stocks do
    member do
      get 'request', :action => 'new_request'
      post 'request', :action => 'create_request'
    end
  end

  resources :stock_requests

  resources :masterfiles do
    collection { post :import }
  end

end

app/controllers/journal_types_controller.rb
class JournalTypesController < ApplicationController
  before_action :set_journal_type, only: [:show, :edit, :update, :destroy]

  # GET /journal_types
  # GET /journal_types.json
  def index
    @journal_types = JournalType.all
  end

  # GET /journal_types/1
  # GET /journal_types/1.json
  def show
  end

  # GET /journal_types/new
  def new
    @journal_type = JournalType.new
  end

  # GET /journal_types/1/edit
  def edit
  end

  # POST /journal_types
  # POST /journal_types.json
  def create
    @journal_type = JournalType.new(journal_type_params)

    respond_to do |format|
      if @journal_type.save
        format.html { redirect_to @journal_type, notice: 'Journal type was successfully created.' }
        format.json { render :show, status: :created, location: @journal_type }
      else
        format.html { render :new }
        format.json { render json: @journal_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journal_types/1
  # PATCH/PUT /journal_types/1.json
  def update
    respond_to do |format|
      if @journal_type.update(journal_type_params)
        format.html { redirect_to @journal_type, notice: 'Journal type was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal_type }
      else
        format.html { render :edit }
        format.json { render json: @journal_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journal_types/1
  # DELETE /journal_types/1.json
  def destroy
    @journal_type.destroy
    respond_to do |format|
      format.html { redirect_to journal_types_url, notice: 'Journal type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal_type
      @journal_type = JournalType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_type_params
      params.require(:journal_type).permit(:name, :effect)
    end
end

app/helpers/journal_types_helper.rb
module JournalTypesHelper
end

app/views/journal_types/_form.html.erb
<%= form_for(@journal_type) do |f| %>
  <% if @journal_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal_type.errors.count, "error") %> prohibited this journal_type from being saved:</h2>

      <ul>
      <% @journal_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :effect %><br>
    <%= f.number_field :effect %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journal_types/edit.html.erb
<h1>Editing Journal Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @journal_type %> |
<%= link_to 'Back', journal_types_path %>

app/views/journal_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Journal Types</h1>

<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Effect</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @journal_types.each do |journal_type| %>
        <tr>
          <td><%= journal_type.name %></td>
          <td><%= journal_type.effect %></td>
          <td><%= link_to 'Show', journal_type %></td>
          <td><%= link_to 'Edit', edit_journal_type_path(journal_type) %></td>
          <td><%= link_to 'Destroy', journal_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Journal type', new_journal_type_path %>

app/views/journal_types/new.html.erb
<h1>New Journal Type</h1>

<%= render 'form' %>

<%= link_to 'Back', journal_types_path %>

app/views/journal_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @journal_type.name %>
</p>

<p>
  <strong>Effect:</strong>
  <%= @journal_type.effect %>
</p>

<%= link_to 'Edit', edit_journal_type_path(@journal_type) %> |
<%= link_to 'Back', journal_types_path %>