config/routes.rb
Rails.application.routes.draw do

  root 'stocks#index'
  
  resources :categories
  resources :journals
  resources :journal_types
 
  resources :locations
  resources :products

 
  resources :stocks do
    member do
      get 'request', :action => 'new_request'
      post 'request', :action => 'create_request'
    end
  end

  resources :stock_requests

  resources :masterfiles do
    collection { post :import }
  end

end

app/models/journal.rb
class Journal < ActiveRecord::Base
	after_save :update_stocks
  belongs_to :location
  belongs_to :product
  belongs_to :journal_type

  private

  def update_stocks
  	stock = Stock.where("location_id =? and product_id = ?",self.location_id, self.product_id).first
  	if stock 
  		if self.journal_type.effect == 1
  			stock.qty += self.qty
  		end

  		if self.journal_type.effect == 2
  			stock.qty -= self.qty
  		end
  		
  		stock.save
  	else
  		Stock.create(location_id: self.location_id, product_id: self.product_id, qty: self.qty)
  	end
  end
end

app/models/journal_type.rb
class JournalType < ActiveRecord::Base
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]
  before_action :set_journal_reference, only: [:new]
  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    def set_journal_reference
      @locations = Location.all
      @products = Product.all
      @journal_types = JournalType.all
    end

    

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:location_id, :product_id, :journal_type_id, :qty)
    end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for(@journal) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :journal_type_id %><br>
    <%= f.text_field :journal_type_id %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.number_field :qty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing Journal</h1>

<%= render 'form' %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Journals</h1>

<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Location</th>
        <th>SKU Code</th>
        <th>Product</th>
        <th>Journal type</th>
        <th>Qty</th>
        <th>Date Created</th>
      </tr>
    </thead>

    <tbody>
      <% @journals.each do |journal| %>
        <tr>
          <td><%= journal.location.name %></td>
          <td><%= journal.product.sku %></td>
          <td><%= journal.product.name %></td>
          <td><%= journal.journal_type.name %></td>
          <td><%= journal.qty %></td>
          <td><%= journal.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<br>

<%= link_to 'New Journal', new_journal_path %>

app/views/journals/new.html.erb
<h1>New Journal</h1>

<%= render 'form' %>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @journal.location %>
</p>

<p>
  <strong>Product:</strong>
  <%= @journal.product %>
</p>

<p>
  <strong>Journal type:</strong>
  <%= @journal.journal_type %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @journal.qty %>
</p>

<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', journals_path %>