config/routes.rb
Rails.application.routes.draw do

  root 'stocks#index'
  
  resources :categories
  resources :journals
  resources :journal_types
 
  resources :locations
  resources :products

 
  resources :stocks do
    member do
      get 'request', :action => 'new_request'
      post 'request', :action => 'create_request'
    end
  end

  resources :stock_requests

  resources :masterfiles do
    collection { post :import }
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spare Parts System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Spare Parts System</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
             <li>
              <%= link_to 'Categories', categories_path %>
            </li>
            <li>
            	<%= link_to 'Products', products_path %>
            </li>
            <li>
            	<%= link_to 'Locations', locations_path %>
            </li>
            <li>
            	<%= link_to 'Stocks', stocks_path %>
            </li>
            <li>
              <%= link_to 'Journal Types', journal_types_path %>
            </li>

            <li>
              <%= link_to 'Journals', journals_path %>
            </li>

            <li>
              <%= link_to 'Stock Requests', stock_requests_path %>
            </li>
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <%= yield %>

    </div> <!-- /container -->



</body>
</html>